//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Template_Test.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class SinhVien
    {
        [Required(ErrorMessage = "Mã sinh viên không được để trống")]
        public string maSV { get; set; }

        [Required(ErrorMessage = "Họ sinh viên không được để trống")]
        public string hoSV { get; set; }

        [Required(ErrorMessage = "Tên sinh viên không được để trống")]
        public string tenSV { get; set; }

        [Required(ErrorMessage = "Ngày sinh không được để trống")]
        public Nullable<System.DateTime> ngaySinh { get; set; }
        public string gioiTinh { get; set; }
        public string anhSV { get; set; }
        public string diaChi { get; set; }
        public string maLop { get; set; }
    
        public virtual Lop Lop { get; set; }
    }
}
